[package]
name = "chessbik-board"
version = "0.1.0"
edition = "2021"

[dependencies]
chessbik-commons = { git = "https://github.com/necromfox/chessbik-commons" }
derive_more = "^0.99.17"

[features]
rich_piece_display = []