use crate::BoardNew;

pub use super::*;

impl BoardNew for Board {
    fn new() -> Self {
        Self {
            cells: [
                Cell::BPAWN,
                Cell::BPAWN,
                Cell::BPAWN,
                Cell::NONE,
                Cell::NONE,
                Cell::NONE,
                Cell::WPAWN,
                Cell::WPAWN,
                Cell::WPAWN,
                Cell::BPAWN,
                Cell::NONE,
                Cell::WPAWN,
                Cell::BPAWN,
                Cell::NONE,
                Cell::WPAWN,
                Cell::BPAWN,
                Cell::NONE,
                Cell::WPAWN,
                Cell::WKNIGHT,
                Cell::WQUEEN,
                Cell::WKNIGHT,
                Cell::WROOK,
                Cell::WKING,
                Cell::WROOK,
                Cell::WBISHOP,
                Cell::WMAGE,
                Cell::WBISHOP,
                Cell::WPAWN,
                Cell::NONE,
                Cell::BPAWN,
                Cell::WPAWN,
                Cell::NONE,
                Cell::BPAWN,
                Cell::WPAWN,
                Cell::NONE,
                Cell::BPAWN,
                Cell::BKNIGHT,
                Cell::BQUEEN,
                Cell::BKNIGHT,
                Cell::BROOK,
                Cell::BKING,
                Cell::BROOK,
                Cell::BBISHOP,
                Cell::BMAGE,
                Cell::BBISHOP,
                Cell::WPAWN,
                Cell::WPAWN,
                Cell::WPAWN,
                Cell::NONE,
                Cell::NONE,
                Cell::NONE,
                Cell::BPAWN,
                Cell::BPAWN,
                Cell::BPAWN,
            ],
        }
    }
}
